In [1]:
import pandas as pd
import numpy as np
#import matplotlib as plt
#import random 

In [2]:
with open('features.txt') as f:
    lines = [line.rstrip() for line in f]

In [3]:
X_train = pd.read_csv('X_train.txt',delim_whitespace=True,names=lines)
Y_train=pd.read_csv('Y_train.txt',delim_whitespace=True,names=["class"])
X_train=np.array(X_train)
Y_train=np.array(Y_train)
Y_train=Y_train.reshape(len(X_train))

In [4]:
X_test = pd.read_csv('X_test.txt',delim_whitespace=True,names=lines)
Y_test=pd.read_csv('Y_test.txt',delim_whitespace=True,names=["class"])
X_test=np.array(X_test)
Y_test=np.array(Y_test)
Y_test=Y_test.reshape(len(X_test))


In [5]:
correctclass=0
errors=[]
classification=np.zeros((6,6))   #initialize these as no of possible classification clusters
for i in range(len(X_test)):
    kind=np.zeros(6)
    dist=np.sum((X_train-X_test[i])**2,axis=1)
    a=np.argsort(dist)[:10]
    #print(a)
    for x in a :
        #print(Y_train[x])
        kind[Y_train[x]-1]+=1
    
    classified = (np.argmax(kind))+1
    #print(classified,Y_test[i])
    if classified ==Y_test[i]:
        correctclass+=1
    else :
        errors.append([i,Y_test[i],classified])
    classification[Y_test[i]-1][classified-1]+=1

print("correctly classified count:",correctclass) 
#print("error classifications:",errors)
print("clasifications count")
print(classification)

correctly classified count: 2672
clasifications count
[[486.   0.  10.   0.   0.   0.]
 [ 36. 431.   4.   0.   0.   0.]
 [ 51.  41. 328.   0.   0.   0.]
 [  0.   4.   0. 409.  78.   0.]
 [  0.   0.   0.  47. 485.   0.]
 [  0.   0.   0.   2.   2. 533.]]


Here all the tuples in the errors are  in the format [iteration(data point row number ),actual,classified as ] 